# This configuration file contains all the inputs parameters needed to run a
# simulation with the code HFPx2D

# Mesh parameters
Number_of_nodes = 241 # Remember: Nelts = Nnodes - 1
Half_fault_length = 10.0

# Material parameter
Plain_strain_modulus = 1.0

# Fluid parameters
Fluid_compressibility = 1.0
Fluid_viscosity = 3.0e-3
Density = 1.0

# Dilatancy parameters
Initial_hydraulic_width = 0.6
Increment_of_dilatancy = 0.0
Slip_dw_for_dilatancy = 1.0

# Layers parameters
# Layer1
id_layer1 = 1;
First_element_layer1 = 1;
Last_element_layer1 = 100;
Cohesion_layer1 = 0.0
Peak_friction_coefficient_layer1 = 1.0
Residual_friction_coefficient_layer1 = 0.6
Slip_dw_for_friction_layer1 = 1.0
#Layer2
id_layer2 = 2;
First_element_layer2 = 101;
Last_element_layer2 = 180;
Cohesion_layer2 = 0.0
Peak_friction_coefficient_layer2 = 2.0
Residual_friction_coefficient_layer2 = 0.6
Slip_dw_for_friction_layer2 = 1.0
#Layer3
id_layer3 = 3;
First_element_layer3 = 181;
Last_element_layer3 = 240;
Cohesion_layer3 = 0.0
Peak_friction_coefficient_layer3 = 3.0
Residual_friction_coefficient_layer3 = 0.6
Slip_dw_for_friction_layer3 = 1.0

# Stress state parameters + inital pore pressure
Ambient_normal_stress = 1.0
Ambient_pore_pressure = 0.0

# Fluid injection parameters
Source = 0.0
Constant_overpressure = 0.5 # 0.5*(Ambient_normal_stress-Ambient_pore_pressure)

# Simulation parameters
t_max = 0.625
t_0plus = 0.0001
TimeStep_max = 0.0005
TimeStep_min = 0.00005
itermax_MCcriterion = 100
itermax_nonlinsystem = 100
tolerance = 10e-6
under_relaxation_parameter = 0.6
