#
# HFPx2D project.
#
# Created by Lorenzo Benedetti on 06.09.17.
# Copyright (c) ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland,
# Geo-Energy Laboratory, 2016-2017.  All rights reserved.
# See the LICENSE.TXT file for more details.
#
#


###########   GEOMETRY   ###########
[geometry]
    #### Automatic mesh generation: FOR 1D MESHES ONLY ####

    # type of mesh generation
    mesh_generation = "automatic"

    # number of fractures (must coincide with following data
    number_of_fractures = 3

    # interpolation order of the elements (the same for every fracture)
    interpolation_order = 1


    # start the description of the fracture creation

[geometry.fracture0] # linear mesh in the vertical direction

        # name of the meshed fracture
        name_of_fracture = "A first fracture"

        # start of the mesh
        x_1 = 0.0
        y_1 = 0.0

        # end of the mesh
        x_2 = 0.0
        y_2 = 5.0

        # number of elements
        number_of_elements=10

        # material properties are independent
        material_ID=0


[geometry.fracture1]
        name_of_fracture = "A second fracture"

        x_1 = 1.0
        y_1 = 2.345

        x_2 = 5.887
        y_2 = -7.443

        number_of_elements=15

        material_ID=1

[geometry.fracture2]

        name_of_fracture = "A second fracture with the material of the second one"

        x_1 = -5.0
        y_1 = -3.0

        x_2 = 2.0
        y_2 = 1.2

        number_of_elements=5

        material_ID=1


########################################################################################################################

[properties]

    Young_modulus=1.0
    Poisson_ratio=0.24

    ## Also available
    # Lame_first
    # Bulk_modulus
    # Shear_modulus or Lame_second

    # Properties of existing fluid in the fault
    fluid_law = "Newtonian"
    fluid_density = 1.0
    fluid_compressibility = 1.0
    fluid_viscosity = 3.0e-3

    number_of_materials = 2


[properties.material0]
        solid_evolution_type = "Cohesive Zone Model"

        cohesive_zone_type = "Pure Opening"

        # Pure opening CZM
        failure_stress = 1.0e6
        max_opening = 0.05
        # fracture_energy is available as well

        flow_evolution_type = "Constant"

        permeability = 1.0


[properties.material1]
        solid_evolution_type = "Cohesive Zone Model"

        cohesive_zone_type = "Pure Shear"

        failure_stress = 1.0e6
        max_slip = 0.1

        flow_evolution_type = "Dilatancy dependence"

        initial_permeability = 0.5

        opening_increase_per_slip = 0.01

        final_permeability = 1.0



