Number_of_nodes = 241
Plain_strain_modulus = 1.0
Density = 1.0
Cohesion = 0.0
Fluid_compressibility = 1.0
Fluid_viscosity = 3.0e-3
Initial_hydraulic_width = 0.6
Increment_of_dilatancy = 0.0
Slip_dw_for_friction_layer1 = 1.0
Slip_dw_for_friction_layer2 = 1.0
Slip_dw_for_friction_layer3 = 1.0
Slip_dw_for_dilatancy = 1.0
Peak_friction_coefficient_layer1 = 1.0
Residual_friction_coefficient_layer1 = 0.6
Peak_friction_coefficient_layer2 = 1.0
Residual_friction_coefficient_layer2 = 0.6
Peak_friction_coefficient_layer3 = 1.0
Residual_friction_coefficient_layer3 = 0.6
Ambient_normal_stress = 1.0
Ambient_pore_pressure = 0.0
Ambient_shear_stress = 0.75   # 0.75 * (Peak_fric * (Ambient_normal_stress - Ambient_pore_pressure))
Constant_overpressure = 0.5   # 0.5 * (Ambient_normal_stress - Ambient_pore_pressure)
Source = 0.0
Half_fault_length = 10.0
TimeStep_max = 0.005
TimeStep_min = 0.0001