############  GEOMETRY  ############
 
[Geometry]
 
    mesh_generation = "automatic"
 
    number_of_fractures = 1
 
    interpolation_order = 1
 
[Geometry.fracture1]
 
    name_of_fracture = "A first fracture"
 
    x_1 = -10.0
    y_1 = 0.0
 
    x_2 = 10.0
    y_2 = 0.0
 
    number_of_elements = 1000
 
    material_ID = 1
 
############  PROPERTIES  ############
 
[Properties]
 
    young_modulus = 1.0
    poisson_ratio = 0.0
 
    fluid_law = "Newtonian"
    fluid_density = 1.0
    fluid_compressibility = 1.0
    fluid_viscosity = 3.0e-3
 
    number_of_materials = 1
 
[Properties.material1]
 
    solid_evolution_type = "Cohesive Zone Model"
 
    cohesive_zone_type = "Pure Shear"
 
    peak_friction_coefficient = 1.0
 
    residual_friction_coefficient = 0.6
 
    fracture_evolution_type = "Pure Shear"
 
    initial_permeability = 0.36
 
    increment_permeability = 0.0
 
    residual_slip = 0.4
 
    initial_hydraulic_width = 0.6
 
    increment_hydraulic_width = 0.12
 
[Loading_Conditions]
 
    far_field_vertical_stress = 1.0
 
    far_field_horizontal_stress = 0.55
 
    ambient_pore_pressure = 0.0

[Simulation_Parameters]

    constant_overpressure = 0.5

    initial_time = 0.001

    initial_time_step = 0.0001

    time_step_max = 0.0001

    final_time = 0.4

    expl_impl = false  # set "true" for explicit-implicit time integration scheme

    QD = false   # set "true" for Quasi-Dynamic simulation (including damping term)

    dilat_plast = 0.3  # increment_hydraulic_width / residual_slip
