Number_of_nodes = 241
Plain_strain_modulus = 1.0
Density = 1.0
Cohesion = 0.0
Fluid_compressibility = 1.0
Fluid_viscosity = 3.0e-3
Initial_value_of_dilatancy = 0.6
Increment_of_dilatancy = 0.03
Slip_dw_for_friction = 1.0
Slip_dw_for_dilatancy = 1.0
Peak_friction_coefficient = 1.0
Residual_friction_coefficient = 0.6
Ambient_normal_stress = 1.0
Ambient_pore_pressure = 0.0
Source = 0.0
Half_fault_length = 10.0
TimeStep_max = 0.0005
TimeStep_min = 0.00001